production:
  adapter: mysql2
  database: tracks
  username: tracks
  host: db
  password: <type your password here>
  encoding: utf8

#production:
#  adapter: sqlite3
#  database: db/tracks.sqlite3.db
#  pool: 5
#  timeout: 5000
